command:
  - streamlit
  - run
  - app.py
  - --server.port=8000
  - --server.address=0.0.0.0

env:
  - name: CATALOG
    value: "serverless_sandbox_hsze05_catalog"
  - name: SCHEMA
    value: "denso_demo"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "2e69b709a9fe757a"
